import type { Metadata } from "next";
import ByLine from "./ui/portfolio/by-line";
import Socials from "./ui/portfolio/socials";
import SideNav from "./ui/portfolio/side-nav";
import { redditMono } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mariam Batool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={redditMono.className}>
        <div className="flex flex-col h-screen sm:flex-row ">
        <div className="w-2/5 flex justify-center flex-col px-8 pt-20 bg-slate-200 overflow-y-hidden">
          <div className="h-500 w-500 mb-20">
            <a href="/"><ByLine/></a>
          </div>
          <div className="ml-8 mb-5">
            <SideNav/>
          </div>
          <div className="flex flex-row justify-start items-center gap-x-4">
            <Socials/>
          </div>
        </div>
        <div className="w-3/5 bg-slate-50 px-8 overflow-y-auto">
          {children}
        </div>
    </div>    
    </body>
    </html>
  );
}
